name: Development

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
