name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout the repo
      - run: npm ci # install packages
      - run: npm test # run tests (configured to use jest-junit reporter)
      - uses: actions/upload-artifact@v4 # upload test results
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: jest-junit.xml
  coverage:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/download-artifact@v2 # download test results
        with:
          name: test-results
          path: jest-junit.xml
      - uses: actions/setup-node@v2 # setup node
        with:
          node-version: "20"
      - run: npm install -g jest-sonar-reporter # install jest-sonar-reporter
      - run: jest-sonar-reporter # generate coverage report
      - uses: sonarsource/sonarcloud-github-action@master # run sonarcloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=oussamafatnassi
            -Dsonar.projectKey=OussamaFatnassi_electronCours
